# https://docs.microsoft.com/azure/devops/pipelines

pool:
  vmImage: 'windows-2019'

variables:
  solution: 'sscms.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  version: 7.0.$(Build.BuildNumber)

steps:
- task: DotNetCoreInstaller@0
  displayName: install dotnet
  inputs:
    version: '3.0.100'

- task: NuGetToolInstaller@1
  displayName: install nuget
  inputs:
    versionSpec: 
    checkLatest: true

- script: dotnet restore $(solution)
  displayName: dotnet restore

- script: nuget restore src/SS.CMS.Cli/packages.config -PackagesDirectory ./packages
  displayName: nuget restore SS.CMS.Cli

- script: nuget restore src/SS.CMS.Web/packages.config -PackagesDirectory ./packages
  displayName: nuget restore SS.CMS.Web

- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- script: dotnet pack /p:PackageVersion=$(version)
  displayName: dotnet pack
